### ISSUE TITLE
Repository is not public but stable PCB version is pointing to it.

### ISSUE THREAD

**Issue by Phil5555** [rerebebekkkkaaaa/BexxiGun#5]
Hi there,

I just found out, that the new, shiny, stable PCB version is referencing your great repository for source code.
Yet, beside of you, I'm the only one who can access these sources.
Might be that this is because you are storing your private passwords in here.

I think both should change:
* Your passwords should be removed from the sources
* Your repository should become public

Regards
Phil

**Comment by rerebebekkkkaaaa** [comment]
Now the perfectly designed PCB is, alongside the almost perfect SW in a public repo 🥳 !
